### PR TITLE
drm/panel: Fix default values for Waveshare 7.9 inch DSI touchscreen

### PR DESCRIPTION
**Pull request by ilarrain**
This fixes touchscreen calibration, axis swapping and inversion.

As referenced in https://github.com/raspberrypi/linux/issues/5550

### CODE REVIEW

**Comment by 6by9** [comment]
Increasing the size to 4096x4096 is definitely wrong.

I don't have the 7.9" panel, but the current configuration is based on https://github.com/waveshare/Waveshare-DSI-LCD/issues/4#issuecomment-1509490884 where it was reported that the original Waveshare line was ```dtoverlay=WS_xinchDSI_Touch,I2C_bus=10,invertedx,invertedy```, which also matches the Waveshare script  at https://github.com/waveshare/Waveshare-DSI-LCD/blob/main/6.1.21/64/pi4/WS_xinchDSI.sh#L64.

Please install the Waveshare drivers and confirm whether the mapping there is correct. If so, please provide the config.txt settings that they are using.

**Comment by ilarrain** [comment]
> Increasing the size to 4096x4096 is definitely wrong.
> 
> I don't have the 7.9" panel, but the current configuration is based on https://github.com/waveshare/Waveshare-DSI-LCD/issues/4#issuecomment-1509490884 where it was reported that the original Waveshare line was ```dtoverlay=WS_xinchDSI_Touch,I2C_bus=10,invertedx,invertedy```, which also matches the Waveshare script  at https://github.com/waveshare/Waveshare-DSI-LCD/blob/main/6.1.21/64/pi4/WS_xinchDSI.sh#L64.
> 
> Please install the Waveshare drivers and confirm whether the mapping there is correct. If so, please provide the config.txt settings that they are using.

Thank you very much for the original driver.


Definitely wrong? With the default config, only a small touch area (about
2x2 cm) was mapped to the whole screen. I've gradually changed the value on
each axis, and the touch area was getting bigger and bigger: 400 > 1080 >
2000 > 3000 > 4000 (it was close to perfect, but not quite) > 4200 (it was
too big) > 4096 (it was perfect, ok both axis).
4096 = 2^12. 12 bit resolution on each axis.

Another user confirmed the fix as working on his panel:
https://github.com/raspberrypi/linux/issues/5550#issuecomment-1668239791

I don't know if it applies to other panels, but at list on mine, and
@beletruz, the patch fixed the issues. Maybe other panel models also use 12
bit resolution on both axis (4096).

I can't install waveshare's driver. At least without disassembling my project, and installing one of
the OS/kernels for which waveshare have compiled the proprietary driver.
That's why I went the open source route.

**Comment by beletruz** [comment]
I can confirm it works like a charm

**Comment by ilarrain** [comment]
I've botched the quote in the previous reply (replied by email). I'm trying to fix it here:

> Increasing the size to 4096x4096 is definitely wrong.
> 
> I don't have the 7.9" panel, but the current configuration is based on https://github.com/waveshare/Waveshare-DSI-LCD/issues/4#issuecomment-1509490884 where it was reported that the original Waveshare line was ```dtoverlay=WS_xinchDSI_Touch,I2C_bus=10,invertedx,invertedy```, which also matches the Waveshare script  at https://github.com/waveshare/Waveshare-DSI-LCD/blob/main/6.1.21/64/pi4/WS_xinchDSI.sh#L64.
> 
> Please install the Waveshare drivers and confirm whether the mapping there is correct. If so, please provide the config.txt settings that they are using.

Thank you very much for the original driver.


Definitely wrong? With the default config, only a small touch area (about
2x2 cm) was mapped to the whole screen. I've gradually changed the value on
each axis, and the touch area was getting bigger and bigger: 400 > 1080 >
2000 > 3000 > 4000 (it was close to perfect, but not quite) > 4200 (it was
too big) > 4096 (it was perfect, ok both axis).
4096 = 2^12. 12 bit resolution on each axis.

Another user confirmed the fix as working on his panel:
https://github.com/raspberrypi/linux/issues/5550#issuecomment-1668239791

I don't know if it applies to other panels, but at list on mine, and
@beletruz, the patch fixed the issues. Maybe other panel models also use 12
bit resolution on both axis (4096).

I can't install waveshare's driver. At least without disassembling my project, and installing one of
the OS/kernels for which waveshare have compiled the proprietary driver.
That's why I went the open source route.

**Comment by 6by9** [comment]
I say it's wrong as that isn't how the Goodix GT911 touch controller works. Datasheet at https://www.crystalfontz.com/controllers/GOODIX/GT911/464/
It's possible that Waveshare have hacked a touch device to look a bit like a GT911, but that would feel a little strange.

In [the original discussion of the driver](https://github.com/waveshare/Waveshare-DSI-LCD/issues/4#issuecomment-1509490884), the 7.9" panel was confirmed as working with ```dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,invx,swapxy,sizex=400,sizey=1280```, but 
> However, the touch movement is happening in the opposite direction. For the waveshare original driver I had to have this line dtoverlay=WS_xinchDSI_Touch,I2C_bus=10,invertedx,invertedy

That's how the overlay ended up as it is with inverted-x and inverted-y.
@mbhangui any chance you could confirm whether the Waveshare 7.9" driver is working for you with touch correctly please?

**Comment by mbhangui** [comment]
> In [the original discussion of the driver](https://github.com/waveshare/Waveshare-DSI-LCD/issues/4#issuecomment-1509490884), the 7.9" panel was confirmed as working with `dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,invx,swapxy,sizex=400,sizey=1280`, but
> 
> > However, the touch movement is happening in the opposite direction. For the waveshare original driver I had to have this line dtoverlay=WS_xinchDSI_Touch,I2C_bus=10,invertedx,invertedy
> 
> That's how the overlay ended up as it is with inverted-x and inverted-y. @mbhangui any chance you could confirm whether the Waveshare 7.9" driver is working for you with touch correctly please?

Tried this just now. The display works. But the touch is weird.  Let me know if you need me to do anything.

```
$ uname -a
Linux HiFIBerry 6.1.44-v8+ #1670 SMP PREEMPT Wed Aug  9 11:56:17 BST 2023 aarch64 GNU/Linux
$ grep dsi /boot/config.txt
dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,sizex=4096,sizey=4096
```

**Comment by beletruz** [comment]
>  > In [the original discussion of the driver](https://github.com/waveshare/Waveshare-DSI-LCD/issues/4#issuecomment-1509490884), the 7.9" panel was confirmed as working with `dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,invx,swapxy,sizex=400,sizey=1280`, but
> > 
> > > However, the touch movement is happening in the opposite direction. For the waveshare original driver I had to have this line dtoverlay=WS_xinchDSI_Touch,I2C_bus=10,invertedx,invertedy
> > 
> > That's how the overlay ended up as it is with inverted-x and inverted-y. @mbhangui any chance you could confirm whether the Waveshare 7.9" driver is working for you with touch correctly please?
> 
> Tried this just now. The display works. But the touch is weird.  Let me know if you need me to do anything.
> 
> ```
> $ uname -a
> Linux HiFIBerry 6.1.44-v8+ #1670 SMP PREEMPT Wed Aug  9 11:56:17 BST 2023 aarch64 GNU/Linux
> $ grep dsi /boot/config.txt
> dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,sizex=4096,sizey=4096
> ```

You also need invx and swapxy

**Comment by mbhangui** [comment]
> 
> You also need invx and swapxy

Tried that too. I have tried all of these below. I have the touch issue with all of them
```
dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,invx,swapxy,sizex=400,sizey=1280
dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,invx,swapxy,sizex=4096,sizey=4096
dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,sizex=4096,sizey=4096
```

**Comment by beletruz** [comment]
> > 
> > You also need invx and swapxy
> 
> Tried that too. I have tried all of these below. I have the touch issue with all of them
> ```
> dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,invx,swapxy,sizex=400,sizey=1280
> dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,invx,swapxy,sizex=4096,sizey=4096
> dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,sizex=4096,sizey=4096
> ```
> 

Try using the overlay compiled by ilarrain, that did the trick for me

**Comment by ilarrain** [comment]
> > > 
> > > You also need invx and swapxy
> > 
> > Tried that too. I have tried all of these below. I have the touch issue with all of them
> > ```
> > dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,invx,swapxy,sizex=400,sizey=1280
> > dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,invx,swapxy,sizex=4096,sizey=4096
> > dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,sizex=4096,sizey=4096
> > ```
> > 
> 
> Try using the overlay compiled by ilarrain, that did the trick for me

sizex and sizey do nothing on the default overlay, they just work on a testing overlay that's not longer available.

If you use the overlay I've compiled ( https://drive.google.com/file/d/1vxbMmwprV20rWj2UMmCCoejJhksR0Og8/view?usp=drivesdk ), just setting `dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch` should suffice. Size, inversions, and axis swap are baked in as defaults for `7_9_inch` panel. The overlay should be placed on /boot/overlays/ on raspberry pi os (overwriting the one included in the OS).

**Comment by mbhangui** [comment]
I tried `dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch`. The touch works in the display's native orientation (portrait/vertical orientation). But I need the display to be rotated by 90 degrees and I was configuring that using the raspberry pi Preferences ---> Screen Configuration. After rotating the display by 90 degrees clockwise, the touch interface still uses the old orientation. What worked for me is by rotating the touch by 270 degrees

This is the change I made by creating the file /etc/X11/xorg.conf.d/40-libinput.conf
```
Section "InputClass"
        Identifier "libinput touchscreen catchall"
        MatchIsTouchscreen "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "TransformationMatrix" "0 1 0 -1 0 1 0 0 1"
EndSection
```

**Comment by ilarrain** [comment]
> I tried `dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch`. The touch works in the display's native orientation (portrait/vertical orientation). But I need the display to be rotated by 90 degrees and I was configuring that using the raspberry pi Preferences ---> Screen Configuration. After rotating the display by 90 degrees clockwise, the touch interface still uses the old orientation. What worked for me is by rotating the touch by 270 degrees
> 
> This is the change I made by creating the file /etc/X11/xorg.conf.d/40-libinput.conf
> ```
> Section "InputClass"
>         Identifier "libinput touchscreen catchall"
>         MatchIsTouchscreen "on"
>         MatchDevicePath "/dev/input/event*"
>         Driver "libinput"
>         Option "TransformationMatrix" "0 1 0 -1 0 1 0 0 1"
> EndSection
> ```

Rotating by overlay works perfectly for me, both in 90, and 270°. See https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README#L4560

`dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch,rotation=270`.

**Pull request merged**
